# Generated by Django 5.0 on 2024-02-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_tax_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vedor',
            new_name='vedors',
        ),
    ]
